### ISSUE TITLE
Issues interfacing with modded characters/assets

### ISSUE THREAD

**Issue by Angelite191** [medeor413/starcheat#21]
It crashes on start up when loading modded characters
New characters are affected as well. Here's the error information.

[for new human character with nothing in inventory]
 Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 175, in **init**
  File "build\gui\mainwindow.py", line 554, in open_file
  File "build\gui\mainwindow.py", line 260, in update
  File "build\gui\mainwindow.py", line 718, in update_bag
  File "build\gui\common.py", line 116, in **init**
  File "build\gui\common.py", line 63, in inv_icon
  File "build\assets\items.py", line 141, in get_item_icon
AttributeError: 'list' object has no attribute 'split'

[for human character with modded items in inventory]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 175, in **init**
  File "build\gui\mainwindow.py", line 554, in open_file
  File "build\gui\mainwindow.py", line 260, in update
  File "build\gui\mainwindow.py", line 718, in update_bag
  File "build\gui\common.py", line 116, in **init**
  File "build\gui\common.py", line 63, in inv_icon
  File "build\assets\items.py", line 137, in get_item_icon
TypeError: argument of type 'NoneType' is not iterable

It also completely fails to register a modded character that I stripped of all modded items., compare images for details.
![screenshot_1](https://cloud.githubusercontent.com/assets/5303834/17158615/9328d064-5365-11e6-8ef6-c9484a38d42d.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/5303834/17158619/960661e8-5365-11e6-97a9-5f93600f06e1.png)

**Comment by rubellyte** [comment]
RE the first error: try [the latest build](https://ci.appveyor.com/api/buildjobs/umt2qe3mxck4a9l5/artifacts/dist/starcheat-b30271c-win64.zip) and see if that's fixed. I'll get to the other one soon.

**Comment by Angelite191** [comment]
Ah, alright. Should I make a new issue if I find a different bug, or would you rather me just update this title and post it here?

**Comment by rubellyte** [comment]
File a separate issue, helps me keep things sorted.

**Comment by rubellyte** [comment]
Closed after eight months without a response.
